import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import Search from "~/components/Search"
import { api } from "~/utils/api";

import "~/styles/globals.css";
import SideBar from "~/components/SideBar";
import Head from "next/head";
import { BookmarksProvider } from "~/context/bookmarkcontext";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <BookmarksProvider>
      <Head>
        <title>Movie-web-t3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#DC143C] min-h-screen">
      <div className=" md:flex px-5 text-white ">
        <div className=" m:w-1/4 md:w-[20%] lg:w-[15%]">
        <SideBar />
        </div>
        <div className="min-h-screen md:border-l md:px-6 md:w-3/4 flex-grow py-3">
          <Search />
          <Component {...pageProps} />
        </div>
      </div>
      </div>
      </BookmarksProvider>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
