import { type AppType } from "next/app";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import SideBar from "~/components/SideBar";
import Head from "next/head";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Movie-web-t3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#0C141F] min-h-screen w-full">
      <div className=" flex px-5 text-white ">
        <div className="col-span- w-1/4 md:w-[20%] lg:w-[15%]">
        <SideBar />
        </div>
        <div className="min-h-screen border-l px-6 w-3/4 flex-grow">
          <Component {...pageProps} />
        </div>
      </div>
      </div>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
